# Generated by Django 5.2.3 on 2025-06-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/productimage')),
                ('phone', models.CharField(default='none')),
                ('delete_status', models.IntegerField(choices=[(1, 'live'), (0, 'Delete')], default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coustomer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
