# Generated by Django 5.2.3 on 2025-06-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customermodels_password_alter_customermodels_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodels',
            name='password',
        ),
        migrations.AlterField(
            model_name='customermodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customermodels',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='customermodels',
            name='phone',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='customermodels',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
