# Generated by Django 5.2.3 on 2025-06-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_sellermodels'),
        ('Products', '0004_alter_productmodels_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerModels',
        ),
    ]
