# Generated by Django 5.2.3 on 2025-06-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_sellermodels'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodels',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Customers.sellermodels'),
        ),
    ]
