# Generated by Django 5.2.3 on 2025-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_productmodels_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
