# Generated by Django 5.2.3 on 2025-06-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_productmodels_created_at'),
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodels',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Seller.sellermodels'),
        ),
    ]
