# Generated by Django 5.2.3 on 2025-06-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productmodels_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodels',
            name='url',
            field=models.URLField(blank=True, help_text='Enter download or access link', max_length=500, null=True),
        ),
    ]
